management:
  context-path: /admin
  
server:
  port: 8083
  
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
     healthcheck:
      enabled: false
  serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: WEAK

  