server:
  port: 8000

zuul:
  # 禁止服务自动添加
  ignoredServices: '*'
  # 手动添加服务
  routes:
    asset:
      path: /asset/**
      serviceId: ASSET
      stripPrefix: false
    users:
      path: /users/**
      url: http://localhost:8081/asset
      
ribbon:
    readTimeout: 5000
    hystrixTimeout: 4500
    execTime: 4000

users:
  ribbon:
    listOfServers: localhost
          
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
     
eureka:
  #instance:
     #metadata-map:
      #zone: '@zone'
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
 
# 设置服务名称  
spring:
  application:
    name: ZUUL